version: 2

jobs:
    build:
        working_directory: ~/app
        docker:
            - image: swift:4.1
        steps:
            - checkout
            - run: swift build -c release
            - run: swift test
